### ISSUE TITLE
Add Warning and Error to Logger

### ISSUE THREAD

**Issue by dfreilich** [buildpack/libbuildpack#2]
Can we add Warning and Error methods to the Logger? In similar loggers (see, for example, [cloudfoundry/libbuildpack/logger.go](https://github.com/cloudfoundry/libbuildpack/blob/master/logger.go#L33-L39)), it provides a useful functionality

**Comment by nebhale** [comment]
`libcfbuildpack` is the appropriate place for this (the buildpack spec only speaks of debug and info to `stderr` and `stdout` respectively).  Transferring now.

**Comment by nebhale** [comment]
This issue was moved to cloudfoundry/libcfbuildpack#8
